### ISSUE TITLE
Weird Quirks

### ISSUE THREAD

**Issue by heathersansone** [heatherkemp/wdi_projectTwo#2]
I used express static to load in my style.css and image assets and it works on my index.html page, but it isn't working at all on the show.html page.  I am having a difficult time troubleshooting the cause because both files are located in the same directory and I copied the head tag code from the index page over to the show page, so it is identical.

I am also having a weird secondary issue where my show page data from the database is printing out to the browser, but terminal is throwing an error.

**Comment by andrewfritz86** [comment]
OK,  looking at it
