### ISSUE TITLE
Query results return null values...

### ISSUE THREAD

**Issue by heathersansone** [heatherkemp/wdi_projectTwo#3]
In my app.get('/') route...
Sung helped me figure out a way to delay the rendering and sending of file out of my forEach loop which I thought was working, but when I add a new topic, it doesn't output anything to the index.html page.  When I console log it, it appears that it's returning null values for everything being received from my database query.  
I have tested in Terminal a SELECT \* FROM topics query which returns all the data, including the ones that are ending up null, so that means they are in the database.
The weirdest part is when I added a comment to the database via Terminal to one of the missing topics, the data suddenly appears on the screen.  Is there some SQL thing that would invalidate all the other data if the COUNT is zero?

**Comment by andrewfritz86** [comment]
Can you push your latest code?
